blank_issues_enabled: false
contact_links:
  - name: â“ Red Hat Developer Hub JIRA
    url: https://issues.redhat.com/browse/RHIDP
    about: Please report any issues or feature requests in JIRA - https://issues.redhat.com/browse/RHIDP
