name: Push

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
      # since we use multi-semantic-release, which assumes that all plugins in the 1.1.x branch
      # are versioned < 1.2, we can only release from main branch. See RHIDP-1720 for more info
      - main
concurrency:
  group: push
  cancel-in-progress: false

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          # don't persist the GITHUB_TOKEN
          # so that semantic-release can use use the generated token
          persist-credentials: false

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ vars.JANUS_IDP_GITHUB_APP_ID }}
          private-key: ${{ secrets.JANUS_IDP_GITHUB_APP_PRIVATE_KEY }}

      - name: Build all packages
        uses: ./.github/actions/build

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Release via semantic-release
        run: |
          echo -n "Loading tags... ";tagsFound="$(git fetch --tags 2>&1)"; echo "found $(echo "$tagsFound" | wc -l) tags."
          npm config set workspaces-update false
          yarn release --ignore-private-packages
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: '--max-old-space-size=8192'
