name: Release Packages

on:
  push:
    branches:
      - main
      # TODO: Remove once 1.2.x is deprecated
      - 1.2.x
      - release-[0-9].[0-9]*

env:
  TURBO_SCM_BASE: ${{ github.event.before }}
  TURBO_SCM_HEAD: ${{ github.sha }}

# enforce only one release action per release branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ vars.JANUS_IDP_GITHUB_APP_ID }}
          private-key: ${{ secrets.JANUS_IDP_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        shell: bash
        run: |
          yarn install

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set NODE_OPTIONS
        id: node_options
        run: |
          # https://stackoverflow.com/questions/48387040/how-do-i-determine-the-correct-max-old-space-size-for-node-js
          NODE_OPTIONS="--max-old-space-size=$(expr $(echo "$(free -m)" | awk '/^Mem:/ {print $2}') - 2048)"
          echo "Using NODE_OPTIONS: $NODE_OPTIONS"
          echo "NODE_OPTIONS=$NODE_OPTIONS" >> $GITHUB_OUTPUT

      - name: Create Release PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore(release): version packages on ${{ github.ref_name }} branch'
          commit: 'chore(release): version packages on ${{ github.ref_name }} branch'
          version: yarn run packages:version
          publish: yarn run packages:publish
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: ${{ steps.node_options.outputs.NODE_OPTIONS }}
